In [2]:
import pandas as pd
import codecs
import datetime
from datetime import datetime

In [3]:
df = pd.read_excel('./Cal_Fire/2013-2018LargeFiresList_Redbook/CAWildlandFires_2013-Feb2020.xlsx', sheet_name='Data')

In [4]:
df.head()

,Fire Department \nIdentification Number \n(FDID),Fire Department Name,Incident \nNumber,Exposure\nNumber,NFIRS IncidentType\nCode and Description,Incident Name,Year,Start \nDate,Containment \nDate,County,...,State,Zip,Cross Streets/Directions/National Grid,Latitude,Longitude,Total \nInjuries,Total \nFatalities,Estimated \nProperty/Contents\nLoss,Total Acres \nBurned,Cause
0,33090,RIVERSIDE CFD,16,0,561 Unauthorized burning,CASTLEROCK TRL MEAD,2013,2013-01-01,2013-01-01 00:27:00,Riverside,...,CA,92570,"21540 BLK DAWES ST, 21500 BLK",33.840233,-117.286983,0,0,0,1.0,CAMPFIRE
1,33090,RIVERSIDE CFD,312,0,"142 Brush, or brush and grass mixture fire",DATE PALM,2013,2013-01-01,2013-01-01 19:03:00,Riverside,...,CA,92254,Half mile north of the Mecca C,33.964933,-116.127000,0,0,0,1.0,MISCELLANEOUS
2,30065,ORANGE COUNTY FIRE AUTHORITY,0000005,0,173 Cultivated trees or nursery stock fire,NaN,2013,2013-01-01,NaN,Orange,...,CA,000000000,NEAR BUENA VISTA ST,0.000000,0.000000,0,0,0,0.2,ARSON
3,19105,LOS ANGELES CITY FD,52,0,173 Cultivated trees or nursery stock fire,NaN,2013,2013-01-01,NaN,Los Angeles,...,CA,91342,PADDOCK ST,0.000000,0.000000,0,0,500,0.0,ARSON
4,19105,LOS ANGELES CITY FD,1384,0,173 Cultivated trees or nursery stock fire,NaN,2013,2013-01-01,NaN,Los Angeles,...,CA,90003,260 E 71ST ST X S SAN PEDRO ST,0.000000,0.000000,0,0,0,0.0,ARSON

In [5]:
df.shape

(134678, 22)

In [6]:
df.columns = df.columns.str.strip().str.strip(r'\\').str.lower().str.replace(' ', '_').str.replace('(', '').str.replace(')', '').str.replace('\\n','_',)
df.columns = df.columns.str.replace('__','_',)
df.columns

Index(['fire_department_identification_number_fdid', 'fire_department_name',
       'incident_number', 'exposure_number',
       'nfirs_incidenttype_code_and_description', 'incident_name', 'year',
       'start_date', 'containment_date', 'county', 'street_address', 'city',
       'state', 'zip', 'cross_streets/directions/national_grid', 'latitude',
       'longitude', 'total_injuries', 'total_fatalities',
       'estimated_property/contents_loss', 'total_acres_burned', 'cause'],
      dtype='object')

In [22]:
df.start_date.head()

0   2013-01-01
1   2013-01-01
2   2013-01-01
3   2013-01-01
4   2013-01-01
Name: start_date, dtype: datetime64[ns]

In [28]:
df['containment_date'] = pd.to_datetime(df['containment_date'], errors='coerce').fillna(df['start_date'])

In [30]:
df.shape

(134678, 22)

In [29]:
df.dtypes

fire_department_identification_number_fdid             int64
fire_department_name                                  object
incident_number                                       object
exposure_number                                        int64
nfirs_incidenttype_code_and_description               object
incident_name                                         object
year                                                   int64
start_date                                    datetime64[ns]
containment_date                              datetime64[ns]
county                                                object
street_address                                        object
city                                                  object
state                                                 object
zip                                                   object
cross_streets/directions/national_grid                object
latitude                                             float64
longitude                                            float64
total_injuries                                         int64
total_fatalities                                       int64
estimated_property/contents_loss                       int64
total_acres_burned                                   float64
cause                                                 object
dtype: object

In [15]:
[pd.to_datetime(i) for i in df['containment_date']]

TypeError: <class 'datetime.time'> is not convertible to datetime

In [108]:
df['containment_date'].fillna(df['start_date'], inplace=True)

In [21]:
df.dtypes

fire_department_identification_number_fdid             int64
fire_department_name                                  object
incident_number                                       object
exposure_number                                        int64
nfirs_incidenttype_code_and_description               object
incident_name                                         object
year                                                   int64
start_date                                    datetime64[ns]
containment_date                                      object
county                                                object
street_address                                        object
city                                                  object
state                                                 object
zip                                                   object
cross_streets/directions/national_grid                object
latitude                                             float64
longitude                                            float64
total_injuries                                         int64
total_fatalities                                       int64
estimated_property/contents_loss                       int64
total_acres_burned                                   float64
cause                                                 object
dtype: object

In [123]:
 datetime.utcfromtimestamp(1356998400000000000)

OSError: [Errno 84] Value too large to be stored in data type

In [117]:
for t in df['containment_date']:
    if t contains ('-'):
        datetime.utcfromtimestamp(df)

SyntaxError: unexpected EOF while parsing (<ipython-input-117-6b2a027a98b6>, line 1)

In [115]:
df.head()

,fire_department_identification_number_fdid,fire_department_name,incident_number,exposure_number,nfirs_incidenttype_code_and_description,incident_name,year,start_date,containment_date,county,...,state,zip,cross_streets/directions/national_grid,latitude,longitude,total_injuries,total_fatalities,estimated_property/contents_loss,total_acres_burned,cause
0,33090,RIVERSIDE CFD,16,0,561 Unauthorized burning,CASTLEROCK TRL MEAD,2013,2013-01-01,2013-01-01 00:27:00,Riverside,...,CA,92570,"21540 BLK DAWES ST, 21500 BLK",33.840233,-117.286983,0,0,0,1.0,CAMPFIRE
1,33090,RIVERSIDE CFD,312,0,"142 Brush, or brush and grass mixture fire",DATE PALM,2013,2013-01-01,2013-01-01 19:03:00,Riverside,...,CA,92254,Half mile north of the Mecca C,33.964933,-116.127000,0,0,0,1.0,MISCELLANEOUS
2,30065,ORANGE COUNTY FIRE AUTHORITY,0000005,0,173 Cultivated trees or nursery stock fire,NaN,2013,2013-01-01,1356998400000000000,Orange,...,CA,000000000,NEAR BUENA VISTA ST,0.000000,0.000000,0,0,0,0.2,ARSON
3,19105,LOS ANGELES CITY FD,52,0,173 Cultivated trees or nursery stock fire,NaN,2013,2013-01-01,1356998400000000000,Los Angeles,...,CA,91342,PADDOCK ST,0.000000,0.000000,0,0,500,0.0,ARSON
4,19105,LOS ANGELES CITY FD,1384,0,173 Cultivated trees or nursery stock fire,NaN,2013,2013-01-01,1356998400000000000,Los Angeles,...,CA,90003,260 E 71ST ST X S SAN PEDRO ST,0.000000,0.000000,0,0,0,0.0,ARSON

In [114]:
df['containment_date']

0         2013-01-01 00:27:00
1         2013-01-01 19:03:00
2         1356998400000000000
3         1356998400000000000
4         1356998400000000000
                 ...
134673    2020-02-17 17:49:00
134674    2020-02-17 14:15:39
134675    2020-02-17 13:39:40
134676    2020-02-18 06:59:26
134677    2020-02-22 20:52:35
Name: containment_date, Length: 134678, dtype: object

In [77]:
coords_df = df.loc[df['latitude']!=0]

In [78]:
coords_df.shape

(34453, 22)

In [79]:
coords_df.isnull().sum()

fire_department_identification_number_fdid       0
fire_department_name                             0
incident_number                                  0
exposurenumber                                   0
nfirs_incidenttypecode_and_description           0
incident_name                                   95
year                                             0
start_date                                       0
containment_date                               906
county                                           0
street_address                                   0
city                                             0
state                                            0
zip                                              0
cross_streets/directions/national_grid        5176
latitude                                         0
longitude                                        0
total_injuries                                   0
total_fatalities                                 0
estimated_property/contentsloss                  0
total_acres_burned                               0
cause                                            0
dtype: int64

In [28]:
coords_df.dtypes

Fire Department \nIdentification Number \n(FDID)             int64
Fire Department Name                                        object
Incident \nNumber                                           object
Exposure\nNumber                                             int64
NFIRS IncidentType\nCode and Description                    object
Incident Name                                               object
Year                                                         int64
Start \nDate                                        datetime64[ns]
Containment \nDate                                          object
County                                                      object
Street Address                                              object
City                                                        object
State                                                       object
Zip                                                         object
Cross Streets/Directions/National Grid                      object
Latitude                                                   float64
Longitude                                                  float64
Total \nInjuries                                             int64
Total \nFatalities                                           int64
Estimated \nProperty/Contents\nLoss                          int64
Total Acres \nBurned                                       float64
Cause                                                       object
dtype: object

In [44]:
coords_df.shape

(34453, 22)

In [80]:
coords_df.head()

,fire_department_identification_number_fdid,fire_department_name,incident_number,exposurenumber,nfirs_incidenttypecode_and_description,incident_name,year,start_date,containment_date,county,...,state,zip,cross_streets/directions/national_grid,latitude,longitude,total_injuries,total_fatalities,estimated_property/contentsloss,total_acres_burned,cause
0,33090,RIVERSIDE CFD,16,0,561 Unauthorized burning,CASTLEROCK TRL MEAD,2013,2013-01-01,2013-01-01 00:27:00,Riverside,...,CA,92570,"21540 BLK DAWES ST, 21500 BLK",33.840233,-117.286983,0,0,0,1.0,CAMPFIRE
1,33090,RIVERSIDE CFD,312,0,"142 Brush, or brush and grass mixture fire",DATE PALM,2013,2013-01-01,2013-01-01 19:03:00,Riverside,...,CA,92254,Half mile north of the Mecca C,33.964933,-116.127000,0,0,0,1.0,MISCELLANEOUS
24,33090,RIVERSIDE CFD,622,0,"142 Brush, or brush and grass mixture fire",HARLEY KNOX BL / HARVILL,2013,2013-01-02,2013-01-02 13:50:00,Riverside,...,CA,92570,"Water District Tower, APN #314",33.862517,-117.263300,0,0,0,0.0,MISCELLANEOUS
25,37555,CDF-SAN DIEGO,139,0,"142 Brush, or brush and grass mixture fire",MC NALLY RD VALLEY_CEN 3,2013,2013-01-02,2013-01-02 12:54:00,San Diego,...,CA,92082,"13800 BLK NICOLES VISTA, 32021",33.290817,-117.026600,0,0,0,0.0,ARSON
42,33555,CDF-RIVERSIDE,961,0,173 Cultivated trees or nursery stock fire,DE PORTOLA RD TEM,2013,2013-01-03,NaN,Riverside,...,CA,92592,"36899 BLK AVENIDA VERDE, 36599",33.517450,-117.019433,0,0,0,0.0,MISCELLANEOUS

In [46]:
coords_df.isnull().sum()

Fire Department \nIdentification Number \n(FDID)       0
Fire Department Name                                   0
Incident \nNumber                                      0
Exposure\nNumber                                       0
NFIRS IncidentType\nCode and Description               0
Incident Name                                         95
Year                                                   0
Start \nDate                                           0
Containment \nDate                                   906
County                                                 0
Street Address                                         0
City                                                   0
State                                                  0
Zip                                                    0
Cross Streets/Directions/National Grid              5176
Latitude                                               0
Longitude                                              0
Total \nInjuries                                       0
Total \nFatalities                                     0
Estimated \nProperty/Contents\nLoss                    0
Total Acres \nBurned                                   0
Cause                                                  0
dtype: int64

In [47]:
df.head()

,fire_department_\nidentification_number_\nfdid,fire_department_name,incident_\nnumber,exposure\nnumber,firs_incidenttype\ncode_and_descriptio,incident_name,year,start_\ndate,containment_\ndate,county,...,state,zip,cross_streets/directions/national_grid,latitude,longitude,total_\ninjuries,total_\nfatalities,estimated_\nproperty/contents\nloss,total_acres_\nburned,cause
0,33090,RIVERSIDE CFD,16,0,561 Unauthorized burning,CASTLEROCK TRL MEAD,2013,2013-01-01,2013-01-01 00:27:00,Riverside,...,CA,92570,"21540 BLK DAWES ST, 21500 BLK",33.840233,-117.286983,0,0,0,1.0,CAMPFIRE
1,33090,RIVERSIDE CFD,312,0,"142 Brush, or brush and grass mixture fire",DATE PALM,2013,2013-01-01,2013-01-01 19:03:00,Riverside,...,CA,92254,Half mile north of the Mecca C,33.964933,-116.127000,0,0,0,1.0,MISCELLANEOUS
2,30065,ORANGE COUNTY FIRE AUTHORITY,0000005,0,173 Cultivated trees or nursery stock fire,NaN,2013,2013-01-01,NaN,Orange,...,CA,000000000,NEAR BUENA VISTA ST,0.000000,0.000000,0,0,0,0.2,ARSON
3,19105,LOS ANGELES CITY FD,52,0,173 Cultivated trees or nursery stock fire,NaN,2013,2013-01-01,NaN,Los Angeles,...,CA,91342,PADDOCK ST,0.000000,0.000000,0,0,500,0.0,ARSON
4,19105,LOS ANGELES CITY FD,1384,0,173 Cultivated trees or nursery stock fire,NaN,2013,2013-01-01,NaN,Los Angeles,...,CA,90003,260 E 71ST ST X S SAN PEDRO ST,0.000000,0.000000,0,0,0,0.0,ARSON

In [81]:
df.head()

,fire_department_identification_number_fdid,fire_department_name,incident_number,exposurenumber,nfirs_incidenttypecode_and_description,incident_name,year,start_date,containment_date,county,...,state,zip,cross_streets/directions/national_grid,latitude,longitude,total_injuries,total_fatalities,estimated_property/contentsloss,total_acres_burned,cause
0,33090,RIVERSIDE CFD,16,0,561 Unauthorized burning,CASTLEROCK TRL MEAD,2013,2013-01-01,2013-01-01 00:27:00,Riverside,...,CA,92570,"21540 BLK DAWES ST, 21500 BLK",33.840233,-117.286983,0,0,0,1.0,CAMPFIRE
1,33090,RIVERSIDE CFD,312,0,"142 Brush, or brush and grass mixture fire",DATE PALM,2013,2013-01-01,2013-01-01 19:03:00,Riverside,...,CA,92254,Half mile north of the Mecca C,33.964933,-116.127000,0,0,0,1.0,MISCELLANEOUS
2,30065,ORANGE COUNTY FIRE AUTHORITY,0000005,0,173 Cultivated trees or nursery stock fire,NaN,2013,2013-01-01,NaN,Orange,...,CA,000000000,NEAR BUENA VISTA ST,0.000000,0.000000,0,0,0,0.2,ARSON
3,19105,LOS ANGELES CITY FD,52,0,173 Cultivated trees or nursery stock fire,NaN,2013,2013-01-01,NaN,Los Angeles,...,CA,91342,PADDOCK ST,0.000000,0.000000,0,0,500,0.0,ARSON
4,19105,LOS ANGELES CITY FD,1384,0,173 Cultivated trees or nursery stock fire,NaN,2013,2013-01-01,NaN,Los Angeles,...,CA,90003,260 E 71ST ST X S SAN PEDRO ST,0.000000,0.000000,0,0,0,0.0,ARSON

In [84]:
df.total_acres_burned.sum()

116975538.09683843

In [85]:
df['exposurenumber'].value_counts

<bound method IndexOpsMixin.value_counts of 0         0
1         0
2         0
3         0
4         0
         ..
134673    0
134674    0
134675    0
134676    0
134677    0
Name: exposurenumber, Length: 134678, dtype: int64>